// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAvxOanVSeWuCGWVwsuWkO8dtA-MacMXUI',
    appId: '1:889750160169:web:f82cbd132f07e9e9f96d38',
    messagingSenderId: '889750160169',
    projectId: 'fir-agent-88842',
    authDomain: 'fir-agent-88842.firebaseapp.com',
    storageBucket: 'fir-agent-88842.appspot.com',
    measurementId: 'G-D6F3VD6MFE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAApiU_8br3dRN_8Ps6aCWu7pXla7wpiDs',
    appId: '1:889750160169:android:c1b75bfb570a2252f96d38',
    messagingSenderId: '889750160169',
    projectId: 'fir-agent-88842',
    storageBucket: 'fir-agent-88842.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADH2MHXVX20EhFPj5LaiRl8aS5eeBYcew',
    appId: '1:889750160169:ios:38962d72a7a280fdf96d38',
    messagingSenderId: '889750160169',
    projectId: 'fir-agent-88842',
    storageBucket: 'fir-agent-88842.appspot.com',
    iosBundleId: 'com.example.firebaseAgent',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyADH2MHXVX20EhFPj5LaiRl8aS5eeBYcew',
    appId: '1:889750160169:ios:ee77c75061009b4bf96d38',
    messagingSenderId: '889750160169',
    projectId: 'fir-agent-88842',
    storageBucket: 'fir-agent-88842.appspot.com',
    iosBundleId: 'com.example.firebaseAgent.RunnerTests',
  );
}
